version: "3.9"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_NAME: test_tech
      DATABASE_USER: root
      DATABASE_PASSWORD: teste123
      DATABASE_HOST: database
    depends_on:
     - database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthcheck"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 40s 
    deploy:
      resources:
          limits:
            cpus: '0.50'
            memory: 128M
          reservations:
            cpus: '0.25'
            memory: 128M 

  database:
    image: "mysql:5"
    environment:
      MYSQL_ROOT_PASSWORD: teste123
      MYSQL_DATABASE: test_tech
    ports:
      - "3306:3306"
    deploy:
      resources:
          limits:
            cpus: '0.50'
            memory: 128M
          reservations:
            cpus: '0.25'
            memory: 128M    