version: "3.9"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      FOO: BAR
    depends_on:
     - database

  database:
    image: "mysql:5"
    environment:
      MYSQL_ROOT_PASSWORD: teste123
      MYSQL_DATABASE: test_tech
    ports:
      - "3306:3306"  