swagger: "2.0"
info:
  description: ""
  version: "0.0.1"
  title: "Swagger Flights API"
host: "localhost:3000"
basePath: "/"
tags:
- name: "flights"
  description: "Operações sobre Voos"
- name: "planes"
  description: "Operações sobre Avioes"
- name: "pilots"
  description: "Operações sobre pilotos"
- name: "cities"
  description: "Operações sobre cidades"
- name: "countries"
  description: "Operações sobre paises"    
schemes:
- "http"
paths:
  /flights:
    post:
      tags:
      - "flights"
      summary: "Adiciona um novo voo"
      description: ""
      operationId: "addFlight"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Dados do voo a ser salvo"
        required: true
        schema:
          $ref: "#/definitions/flights"
      responses:
        "200":
          description: "SUCCESS"
        "500":
          description: "INTERNAL SERVER ERROR"
    get:
      tags:
      - "flights"
      summary: "Retorna todos os voos"
      description: ""
      operationId: "getFlights"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "SUCCESS"
        "500":
          description: "INTERNAL SERVER ERROR"      
  /flights/{flightId}:        
    put:
      tags:
      - "flights"
      summary: "Altera um voo existente"
      description: ""
      operationId: "updateFlight"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "flightId"
        in: "path"
        description: "Id do voo"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Dados que precisam ser alterados no voo selecionado"
        required: true
        schema:
          $ref: "#/definitions/flights"
      responses:
        "200":
          description: "SUCCESS"
        "500":
          description: "INTERNAL SERVER ERROR"
    delete:
      tags:
      - "flights"
      summary: "Deleta um voo existente"
      description: ""
      operationId: "deleteFlight"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "flightId"
        in: "path"
        description: "Id do voo"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "SUCCESS"
        "500":
          description: "INTERNAL SERVER ERROR"
    get:
      tags:
      - "flights"
      summary: "Retorna um voo especifico"
      description: ""
      operationId: "getFlight"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "flightId"
        in: "path"
        description: "Id do voo"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "SUCCESS"
        "500":
          description: "INTERNAL SERVER ERROR"
  /planes:
    post:
      tags:
      - "planes"
      summary: "Adiciona um novo voo"
      description: ""
      operationId: "addPlane"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Dados do aviao a ser salvo"
        required: true
        schema:
          $ref: "#/definitions/planes"
      responses:
        "200":
          description: "SUCCESS"
        "500":
          description: "INTERNAL SERVER ERROR"
    get:
      tags:
      - "planes"
      summary: "Retorna todos os avioes"
      description: ""
      operationId: "getPlanes"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "SUCCESS"
        "500":
          description: "INTERNAL SERVER ERROR"      
  /planes/{planeId}:        
    put:
      tags:
      - "planes"
      summary: "Altera um aviao existente"
      description: ""
      operationId: "updatePlane"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "planeId"
        in: "path"
        description: "Id do voo"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Dados que precisam ser alterados no voo selecionado"
        required: true
        schema:
          $ref: "#/definitions/planes"
      responses:
        "200":
          description: "SUCCESS"
        "500":
          description: "INTERNAL SERVER ERROR"
    delete:
      tags:
      - "planes"
      summary: "Deleta um aviao existente"
      description: ""
      operationId: "deletePlane"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "planeId"
        in: "path"
        description: "Id do voo"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "SUCCESS"
        "500":
          description: "INTERNAL SERVER ERROR"
    get:
      tags:
      - "planes"
      summary: "Retorna um aviao especifico"
      description: ""
      operationId: "getPlane"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "planeId"
        in: "path"
        description: "Id do voo"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "SUCCESS"
        "500":
          description: "INTERNAL SERVER ERROR"      
  /pilots:
    post:
      tags:
      - "pilots"
      summary: "Adiciona um novo piloto"
      description: ""
      operationId: "addPilot"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Dados do piloto a ser salvo"
        required: true
        schema:
          $ref: "#/definitions/pilots"
      responses:
        "200":
          description: "SUCCESS"
        "500":
          description: "INTERNAL SERVER ERROR"
    get:
      tags:
      - "pilots"
      summary: "Retorna todos os pilotos"
      description: ""
      operationId: "getPilot"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "SUCCESS"
        "500":
          description: "INTERNAL SERVER ERROR"      
  /pilots/{pilotId}:        
    put:
      tags:
      - "pilots"
      summary: "Altera um voo existente"
      description: ""
      operationId: "updatePilot"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "pilotId"
        in: "path"
        description: "Id do piloto"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Dados que precisam ser alterados no piloto selecionado"
        required: true
        schema:
          $ref: "#/definitions/pilots"
      responses:
        "200":
          description: "SUCCESS"
        "500":
          description: "INTERNAL SERVER ERROR"
    delete:
      tags:
      - "pilots"
      summary: "Deleta um piloto existente"
      description: ""
      operationId: "deletePilot"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "pilotId"
        in: "path"
        description: "Id do piloto"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "SUCCESS"
        "500":
          description: "INTERNAL SERVER ERROR"
    get:
      tags:
      - "pilots"
      summary: "Retorna um piloto especifico"
      description: ""
      operationId: "getPilots"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "pilotId"
        in: "path"
        description: "Id do piloto"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "SUCCESS"
        "500":
          description: "INTERNAL SERVER ERROR"
  /cities:
    post:
      tags:
      - "cities"
      summary: "Adiciona um novo cities"
      description: ""
      operationId: "addCity"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Dados do cities a ser salvo"
        required: true
        schema:
          $ref: "#/definitions/cities"
      responses:
        "200":
          description: "SUCCESS"
        "500":
          description: "INTERNAL SERVER ERROR"
    get:
      tags:
      - "cities"
      summary: "Retorna todos os voos"
      description: ""
      operationId: "getCities"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "SUCCESS"
        "500":
          description: "INTERNAL SERVER ERROR"      
  /cities/{cityId}:        
    put:
      tags:
      - "cities"
      summary: "Altera um voo existente"
      description: ""
      operationId: "updateCity"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "cityId"
        in: "path"
        description: "Id da cidade"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Dados que precisam ser alterados no cities selecionado"
        required: true
        schema:
          $ref: "#/definitions/cities"
      responses:
        "200":
          description: "SUCCESS"
        "500":
          description: "INTERNAL SERVER ERROR"
    delete:
      tags:
      - "cities"
      summary: "Deleta um cities existente"
      description: ""
      operationId: "deleteCity"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "cityId"
        in: "path"
        description: "Id da cidade"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "SUCCESS"
        "500":
          description: "INTERNAL SERVER ERROR"
    get:
      tags:
      - "cities"
      summary: "Retorna um cities especifico"
      description: ""
      operationId: "getCity"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "cityId"
        in: "path"
        description: "Id da cidade"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "SUCCESS"
        "500":
          description: "INTERNAL SERVER ERROR"
  /countries:
    post:
      tags:
      - "countries"
      summary: "Adiciona um novo countries"
      description: ""
      operationId: "addCountry"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Dados do countries a ser salvo"
        required: true
        schema:
          $ref: "#/definitions/countries"
      responses:
        "200":
          description: "SUCCESS"
        "500":
          description: "INTERNAL SERVER ERROR"
    get:
      tags:
      - "flights"
      summary: "Retorna todos os countries"
      description: ""
      operationId: "getCountries"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "SUCCESS"
        "500":
          description: "INTERNAL SERVER ERROR"      
  /countries/{countryId}:        
    put:
      tags:
      - "countries"
      summary: "Altera um countries existente"
      description: ""
      operationId: "updateCountry"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "countryId"
        in: "path"
        description: "Id do pais"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Dados que precisam ser alterados no countries selecionado"
        required: true
        schema:
          $ref: "#/definitions/countries"
      responses:
        "200":
          description: "SUCCESS"
        "500":
          description: "INTERNAL SERVER ERROR"
    delete:
      tags:
      - "countries"
      summary: "Deleta um countries existente"
      description: ""
      operationId: "deleteCountry"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "countryId"
        in: "path"
        description: "Id do pais"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "SUCCESS"
        "500":
          description: "INTERNAL SERVER ERROR"
    get:
      tags:
      - "countries"
      summary: "Retorna um countries especifico"
      description: ""
      operationId: "getCountry"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "countryId"
        in: "path"
        description: "Id do pais"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "SUCCESS"
        "500":
          description: "INTERNAL SERVER ERROR"
definitions:
  planes:
    type: "object"
    properties:
      model:
        type: "string"
      registry:
        type: "string"
    xml:
      name: "Order"
  countries:
    type: "object"
    properties:
      name:
        type: "string"
    xml:
      name: "countries"
  pilots:
    type: "object"
    properties:
      name:
        type: "string"
    xml:
      name: "pilots"
  cities:
    type: "object"
    properties:
      country:
        type: "integer"
        format: "int64"
      name:
        type: "string"
    xml:
      name: "cities"
  flights:
    type: "object"
    required:
    - "time"
    - "location"
    - "plane"
    - "pilot"
    - "status"
    properties:
      time:
        type: "object"
        properties:
            in:
                type: "string"
            out:
                type: "string"
      location:
        type: "object"
        properties:
            from:
                type: "string"
            to:
                type: "string"
      plane:
        type: "integer"
        format: "int64"
      pilot:
        type: "integer"
        format: "int64"
      status:
        type: "string"                             
    xml:
      name: "flight"

